name: Alerta a ntfy.sh (Hola Mundo)

on:
  push:
    branches: [ "main" ]
    paths:
      - "index.js"
      - "style.css"
      - ".github/workflows/alerta.yml"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificación a ntfy.sh
        run: |
          MSG="🚀 Push en main ejecutado correctamente. Hola Mundo listo!"
          curl \
            -H "Title: CI - Hola Mundo completado" \
            -H "Priority: 4" \
            -H "Tags: rocket,computer" \
            -d "$MSG" \
            https://ntfy.sh/devops-itla
name: Alerta a ntfy.sh (Hola Mundo)

on:
  push:
    branches: [ "main" ]
    paths:
      - "index.js"
      - "style.css"
      - ".github/workflows/alerta.yml"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificación a ntfy.sh
        run: |
          MSG="🚀 Push en main ejecutado correctamente. Hola Mundo listo!"
          curl \
            -H "Title: CI - Hola Mundo completado" \
            -H "Priority: 4" \
            -H "Tags: rocket,computer" \
            -d "$MSG" \
            https://ntfy.sh/devops-itla
