name: Alerta a ntfy.sh (Hola Mundo)

on:
  push:
    branches: [ "main" ]
    paths:
      - "index.js"
      - "style.css"
      - ".github/workflows/alerta.yml"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enviar notificación (ntfy)
        run: |
          MSG="🚀 Push en main por ${{ github.actor }} (commit ${{ github.sha }}) en ${{ github.repository }}"
          curl -sS \
            -H "Title: CI - Notificación" \
            -H "Priority: 4" \
            -H "Tags: rocket,computer" \
            -d "$MSG" \
            https://ntfy.sh/devops-itla

      - name: Setup Node (opcional)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ejecutar Hola Mundo si existe
        run: |
          if [ -f "index.js" ]; then
            echo "Ejecutando index.js..."
            node -v
            node index.js
          else
            echo "index.js no existe en la raíz; omitiendo ejecución."
          fi
